name: Deploy no GitHub Pages

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write     # necess치rio para publicar no Pages 
  id-token: write   # necess치rio para o deploy autenticado

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      # Se tiver build (ex.: gerar pasta dist), coloque aqui.
      # Para HTML simples, vamos s칩 empacotar a raiz do repo.
      - name: Preparar artefato do site
        run: |
          mkdir site
          cp index.html site/

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
